name: 'Slack GitHub Action Status'
description: 'GitHub Actions status updates to Slack as jobs progress'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  debug:
    description: Whether to tell the GitHub client to log details of its requests
    default: false
  important-steps:
    description: 'Comma-separated list of steps that are important to report'
    default: ''
    required: false
  deploy-description:
    description: 'Description of the deployment'
    default: ''
    required: false
  step-identifier:
    description: 'Unique identifier in the name of this step (usually a UUID)'
    required: true
  slack-bot-token:
    description: 'Slack bot token'
    required: true
  slack-channel-id:
    description: 'Slack channel ID'
    required: true
  slack-message-ts:
    description: 'Slack message timestamp to start updating'
  log-job-name:
    description: 'Name of job to use for log URL'
    default: ''
  long-job-duration:
    description: 'Duration in seconds to consider a job long which will cause the final completed message to appear as a new message'
    default: 300
  republish-long-jobs:
    description: 'Whether to republish completed messages for long-running jobs as new messages'
    default: true
  verb:
    description: 'The action being performed (e.g., "deploy", "test"). Used as the base verb in status messages and to derive other verb forms. Past tense can be overridden with verb-past.'
    required: false
    default: 'deploy'
  verb-past:
    description: 'Optional override for the past tense of the verb (e.g., "built" instead of "builded"). If not provided, will be automatically derived from the base verb.'
    required: false

runs:
  using: 'node16'
  main: 'index.js'